# Generated by Django 4.2.2 on 2023-12-26 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='groupextended',
            table='auth_group_extended',
        ),
    ]
