# Generated by Django 4.2.2 on 2023-12-26 02:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_groupextended_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupextended',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupextended',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
